# langgraph_simple_llama_agent_updated.py
# Program demonstrates use of LangGraph for a simple multi-model agent.
# It writes to stdout and asks the user to enter a line of text through stdin.
# It supports three special commands:
#   - verbose: enable tracing information
#   - quiet: disable tracing information
#   - quit / exit / q: terminate the graph
# Empty input is never sent to the models. Instead, the graph routes back to
# the input node and asks again.
# Normal input is passed to a fan-out node, then to both a Llama model and a
# Qwen model in parallel. A join node then prints both model outputs.
# The program uses CUDA if available, then MPS if available, otherwise CPU.
# After the LangGraph graph is created but before it executes, the program
# uses Mermaid to write an image of the graph to the file lg_graph.png.

import os
from typing import TypedDict

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from langchain_huggingface import HuggingFacePipeline
from langgraph.graph import StateGraph, START, END


# =============================================================================
# TRACING CONFIGURATION
# =============================================================================

def decide_whether_to_print(env_var_name: str, default_value: bool = False) -> bool:
    """
    Read an environment variable and convert it into a boolean flag.

    Accepted truthy values: verbose, true, 1, yes
    Accepted falsy values: quiet, false, 0, no

    If the variable is not set, return the provided default value.
    If the variable is set to an unrecognized string, also return the default.
    """
    env_value = os.getenv(env_var_name)

    if env_value is None:
        return default_value

    normalized_value = env_value.strip().lower()

    if normalized_value in {"verbose", "true", "1", "yes"}:
        return True

    if normalized_value in {"quiet", "false", "0", "no"}:
        return False

    return default_value


initial_trace_enabled = decide_whether_to_print("bool_verbose", default_value=True)


# =============================================================================
# DEVICE SELECTION
# =============================================================================

def get_device() -> str:
    """
    Detect and return the best available compute device.

    Returns:
        - "cuda" for NVIDIA GPUs
        - "mps" for Apple Silicon
        - "cpu" otherwise
    """
    if torch.cuda.is_available():
        print("Using CUDA (NVIDIA GPU) for inference")
        return "cuda"

    if torch.backends.mps.is_available():
        print("Using MPS (Apple Silicon) for inference")
        return "mps"

    print("Using CPU for inference")
    return "cpu"


# =============================================================================
# STATE DEFINITION
# =============================================================================
# The state is a TypedDict that flows through all nodes in the graph.
# Each node can read from and write to specific fields in the state.
# LangGraph automatically merges the returned dict from each node into the state.

class AgentState(TypedDict):
    """
    State object that flows through the LangGraph nodes.

    Fields:
    - user_input: The text entered by the user
    - should_exit: Boolean flag indicating whether the graph should terminate
    - trace_enabled: Whether tracing information should be printed
    - llama_response: The response generated by the Llama model
    - qwen_response: The response generated by the Qwen model

    Graph flow:
        START -> get_user_input -> [conditional]
                                  |-> END
                                  |-> get_user_input   (for empty input or mode commands)
                                  |-> fan_out_input -> call_llama ---+
                                                      -> call_qwen ----+-> print_both_responses -> get_user_input
    """
    user_input: str
    should_exit: bool
    trace_enabled: bool
    llama_response: str
    qwen_response: str


# =============================================================================
# MODEL CREATION
# =============================================================================

def create_llm(model_id: str):
    """
    Create and configure an instruction-tuned causal language model from
    Hugging Face and wrap it for LangChain using HuggingFacePipeline.
    """
    device = get_device()

    print(f"Loading model: {model_id}")
    print("This may take a moment on first run as the model is downloaded...")

    tokenizer = AutoTokenizer.from_pretrained(model_id)

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16 if device != "cpu" else torch.float32,
    )

    if device in {"cuda", "mps"}:
        model = model.to(device)

    text_generation_pipeline = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens=256,
        do_sample=True,
        temperature=0.7,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id,
    )

    llm = HuggingFacePipeline(pipeline=text_generation_pipeline)

    print("Model loaded successfully!")
    return llm


# =============================================================================
# RESPONSE CLEANUP
# =============================================================================

def clean_model_response(raw_response: str) -> str:
    """
    Clean a model response so only the assistant text is kept.

    Some text-generation models may continue the transcript and start producing
    another "User:" turn. This function keeps only the first assistant reply.
    """
    cleaned_response = raw_response

    if "Assistant:" in cleaned_response:
        cleaned_response = cleaned_response.split("Assistant:", 1)[1]

    if "\nUser:" in cleaned_response:
        cleaned_response = cleaned_response.split("\nUser:", 1)[0]

    return cleaned_response.strip()


# =============================================================================
# GRAPH CREATION
# =============================================================================

def create_graph(llama_llm, qwen_llm):
    """
    Create the LangGraph state graph with the following nodes:
    1. get_user_input: Reads input from stdin and updates state
    2. fan_out_input: Passes control to both model branches
    3. call_llama: Sends input to the Llama model
    4. call_qwen: Sends input to the Qwen model
    5. print_both_responses: Prints both model responses

    The graph uses a conditional edge after get_user_input so that:
    - quit / exit / q -> END
    - empty input -> get_user_input
    - verbose / quiet -> get_user_input
    - normal input -> fan_out_input
    """

    def get_user_input(state: AgentState) -> dict:
        """
        Prompt the user for input and update the relevant state fields.

        Special commands:
        - quit / exit / q: terminate the graph
        - verbose: enable tracing, then ask for another input
        - quiet: disable tracing, then ask for another input
        - empty input: ask again without calling either model
        """
        trace_enabled = state.get("trace_enabled", False)

        if trace_enabled:
            print("[TRACE] Entering node: get_user_input")

        print("\n" + "=" * 50)
        print("Enter your text ('verbose', 'quiet', or 'quit' to exit):")
        print("=" * 50)

        print("\n> ", end="")
        user_input = input()
        normalized_input = user_input.strip().lower()

        if normalized_input in {"quit", "exit", "q"}:
            if trace_enabled:
                print("[TRACE] Quit command detected. Routing to END.")
            return {
                "user_input": user_input,
                "should_exit": True,
            }

        if normalized_input == "verbose":
            print("Tracing enabled.")
            return {
                "user_input": "",
                "should_exit": False,
                "trace_enabled": True,
            }

        if normalized_input == "quiet":
            if trace_enabled:
                print("[TRACE] Quiet command detected. Tracing will be disabled.")
            return {
                "user_input": "",
                "should_exit": False,
                "trace_enabled": False,
            }

        return {
            "user_input": user_input,
            "should_exit": False,
        }

    def fan_out_input(state: AgentState) -> dict:
        """
        Fan-out node that does not modify the state.
        Its only job is to create a branching point in the graph so the same
        user input can be sent to both models in parallel.
        """
        if state.get("trace_enabled", False):
            print("[TRACE] Entering node: fan_out_input")
            print("[TRACE] Forwarding input to both model branches in parallel.")
        return {}

    def call_llama(state: AgentState) -> dict:
        """
        Invoke the Llama model and store the result in llama_response.
        """
        if state.get("trace_enabled", False):
            print("[TRACE] Entering node: call_llama")

        prompt = f"User: {state['user_input']}\nAssistant:"
        raw_response = llama_llm.invoke(prompt)
        cleaned_response = clean_model_response(raw_response)

        if state.get("trace_enabled", False):
            print("[TRACE] Llama generation complete.")

        return {"llama_response": cleaned_response}

    def call_qwen(state: AgentState) -> dict:
        """
        Invoke the Qwen model and store the result in qwen_response.
        """
        if state.get("trace_enabled", False):
            print("[TRACE] Entering node: call_qwen")

        prompt = f"User: {state['user_input']}\nAssistant:"
        raw_response = qwen_llm.invoke(prompt)
        cleaned_response = clean_model_response(raw_response)

        if state.get("trace_enabled", False):
            print("[TRACE] Qwen generation complete.")

        return {"qwen_response": cleaned_response}

    def print_both_responses(state: AgentState) -> dict:
        """
        Print both model responses after both parallel branches finish.
        """
        if state.get("trace_enabled", False):
            print("[TRACE] Entering node: print_both_responses")
            print("[TRACE] Both model responses are available.")

        print("\n" + "-" * 50)
        print("Llama response")
        print("-" * 50)
        print(state.get("llama_response", ""))

        print("\n" + "-" * 50)
        print("Qwen response")
        print("-" * 50)
        print(state.get("qwen_response", ""))

        return {}

    def route_after_input(state: AgentState) -> str:
        """
        Decide where to go after get_user_input.

        Returns:
        - END: if the user wants to quit
        - "get_user_input": if the input is empty or was a mode command
        - "fan_out_input": if the input should be sent to both models
        """
        if state.get("trace_enabled", False):
            print("[TRACE] Entering router: route_after_input")

        if state.get("should_exit", False):
            if state.get("trace_enabled", False):
                print("[TRACE] Router selected: END")
            return END

        if state.get("user_input", "").strip() == "":
            if state.get("trace_enabled", False):
                print("[TRACE] Router selected: get_user_input")
            return "get_user_input"

        if state.get("trace_enabled", False):
            print("[TRACE] Router selected: fan_out_input")
        return "fan_out_input"

    graph_builder = StateGraph(AgentState)

    graph_builder.add_node("get_user_input", get_user_input)
    graph_builder.add_node("fan_out_input", fan_out_input)
    graph_builder.add_node("call_llama", call_llama)
    graph_builder.add_node("call_qwen", call_qwen)
    graph_builder.add_node("print_both_responses", print_both_responses)

    graph_builder.add_edge(START, "get_user_input")

    graph_builder.add_conditional_edges(
        "get_user_input",
        route_after_input,
        {
            "fan_out_input": "fan_out_input",
            "get_user_input": "get_user_input",
            END: END,
        },
    )

    graph_builder.add_edge("fan_out_input", "call_llama")
    graph_builder.add_edge("fan_out_input", "call_qwen")

    graph_builder.add_edge(["call_llama", "call_qwen"], "print_both_responses")

    graph_builder.add_edge("print_both_responses", "get_user_input")

    graph = graph_builder.compile()
    return graph


# =============================================================================
# GRAPH VISUALIZATION
# =============================================================================

def save_graph_image(graph, filename: str = "lg_graph.png"):
    """
    Generate a Mermaid diagram of the graph and save it as a PNG image.
    """
    try:
        png_data = graph.get_graph(xray=True).draw_mermaid_png()

        with open(filename, "wb") as file_handle:
            file_handle.write(png_data)

        print(f"Graph image saved to {filename}")
    except Exception as exception_message:
        print(f"Could not save graph image: {exception_message}")
        print("You may need to install additional dependencies: pip install grandalf")


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def main():
    """
    Main function that orchestrates the workflow:
    1. Initialize both models
    2. Create the LangGraph
    3. Save the graph visualization
    4. Run the graph once (it loops internally until the user quits)
    """
    print("=" * 50)
    print("LangGraph Simple Agent with Parallel Llama and Qwen")
    print("=" * 50)
    print()

    llama_model_id = "meta-llama/Llama-3.2-1B-Instruct"
    qwen_model_id = "Qwen/Qwen2.5-0.5B"

    print("Loading Llama model...")
    llama_llm = create_llm(llama_model_id)

    print("\nLoading Qwen model...")
    qwen_llm = create_llm(qwen_model_id)

    print("\nCreating LangGraph...")
    graph = create_graph(llama_llm, qwen_llm)
    print("Graph created successfully!")

    print("\nSaving graph visualization...")
    save_graph_image(graph)

    initial_state: AgentState = {
        "user_input": "",
        "should_exit": False,
        "trace_enabled": initial_trace_enabled,
        "llama_response": "",
        "qwen_response": "",
    }

    if initial_trace_enabled:
        print("Tracing starts in verbose mode. Type 'quiet' to disable it.")
    else:
        print("Tracing starts in quiet mode. Type 'verbose' to enable it.")

    graph.invoke(initial_state)


if __name__ == "__main__":
    main()
